language: c
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - compiler: clang
install: sudo apt-get update && sudo apt-get install libcunit1-dev
before_script: autoreconf --install
script: ./configure && make && make check
