/*
 * TaskPriorities.h
 *
 *  Created on: 14 Feb 2016
 *      Author: maora
 */

#ifndef TASKPRIORITIES_H_
#define TASKPRIORITIES_H_

#define OLD_PRIORITY_SCHEME

#define M_TASK_PRIORITY_CLOGGER 1
#define M_TASK_PRIORITY_LOGGER_UDP 1

#define M_TASK_PRIORITY_MAIN_UPDATE_SCHEDULER 4
#define M_TASK_PRIORITY_MODBUS_UPDATE_SCHEDULER 3

#ifdef NEW_PRIORITY_SCHEME
#define M_TASK_PRIORITY_TCP_CONNECTOR_LOW_PRIORITY 1

#define M_TASK_PRIORITY_PSC_MASTER_SERVER 2
#define M_TASK_PRIORITY_PSOC_MANAGER 3
#define M_TASK_PRIORITY_PSC_MESSAGE_HANDLER 4

#define M_TASK_PRIORITY_TCP_CONNECTOR_HIGH_PRIORITY 4
#endif

#ifdef OLD_PRIORITY_SCHEME
#define M_TASK_PRIORITY_PSOC_MANAGER 1
#define M_TASK_PRIORITY_PSC_MASTER_SERVER 4
#define M_TASK_PRIORITY_PSC_MESSAGE_HANDLER 4

#define M_TASK_PRIORITY_TCP_CONNECTOR_LOW_PRIORITY 6
#define M_TASK_PRIORITY_TCP_CONNECTOR_HIGH_PRIORITY 6

#endif


#endif /* TASKPRIORITIES_H_ */
