/*
 * TaskPriorities.h
 *
 *  Created on: 14 Feb 2016
 *      Author: maora
 */

#ifndef TASKPRIORITIES_H_
#define TASKPRIORITIES_H_

#define M_TASK_PRIORITY_CLOGGER 1
#define M_TASK_PRIORITY_PSOC_MANAGER 3
#define M_TASK_PRIORITY_PSC_MESSAGE_HANDLER 4
#define M_TASK_PRIORITY_PSC_MASTER_SERVER 2
#define M_TASK_PRIORITY_LOGGER_UDP 5

#define M_TASK_PRIORITY_TCP_CONNECTOR_LOW_PRIORITY 1
#define M_TASK_PRIORITY_TCP_CONNECTOR_HIGH_PRIORITY 4


#endif /* TASKPRIORITIES_H_ */
