/*
 * version.h
 *
 *  Created on: 12 Dec 2012
 *      Author: maora
 */

#ifndef VERSION_H_
#define VERSION_H_

#define M_FEC_FIRMWARE_VERSION_MAJOR 2
#define M_FEC_FIRMWARE_VERSION_MINOR 1
#define M_FEC_FIRMWARE_VERSION_BUILD 1
#define M_FEC_FIRMWARE_VERSION_REVISION 426

#define M_PSOC_ICD_VERSION_MAJOR 2
#define M_PSOC_ICD_VERSION_MINOR 1
#define M_PSOC_ICD_VERSION_BUILD 0
#define M_PSOC_ICD_VERSION_REVISION 10

#define M_OPC_ICD_VERSION_MAJOR 1
#define M_OPC_ICD_VERSION_MINOR 34
#define M_OPC_ICD_VERSION_BUILD 0
#define M_OPC_ICD_VERSION_REVISION 0


#endif /* VERSION_H_ */
